import { execFile } from "node:child_process";
import { promises as fs } from "node:fs";
import os from "node:os";
import path from "node:path";
import { randomUUID } from "node:crypto";
import { parseChunk } from "../metadata/schema.js";
import { readQr } from "../qr/decode.js";
export interface ShowOptions { interval?: string; gap?: string; loop?: boolean; fullscreen?: boolean; chunks?: string; }
export interface SlideshowImage { src: string; index: number; total: number; }
export function buildSlideshowHtml(images: SlideshowImage[], interval: number, gap: number, loop: boolean, fullscreen: boolean): string {
  const fullscreenButton = fullscreen ? `<button id="fullscreen">Enter fullscreen</button>` : "";
  return `<!doctype html><meta charset="utf-8"><title>qr-source slideshow</title><style>html,body{margin:0;background:#000;color:#fff;height:100%;font:20px system-ui}main{height:100%;display:grid;grid-template-rows:1fr auto;place-items:center}img{max-width:88vw;max-height:80vh;image-rendering:auto;background:#fff;padding:28px}.info{padding:16px;text-align:center}.controls{margin-top:10px;display:flex;gap:8px;justify-content:center}.hint{font-size:13px;color:#bbb;margin-top:8px}button{padding:6px 10px;font:inherit;font-size:14px}</style><main><img id="qr"><div class="info"><span id="count"></span><div class="controls"><button id="restart">First</button><button id="previous">Previous</button><button id="pause">Pause</button><button id="next">Next</button>${fullscreenButton}</div><div class="hint">← / →: previous / next · Space: pause · Esc: exit fullscreen</div></div></main><script>const slides=${JSON.stringify(images)},interval=${interval},gap=${gap},loop=${loop};let i=0,paused=false,timer;const img=document.querySelector('#qr'),count=document.querySelector('#count'),pause=document.querySelector('#pause');document.querySelector('#fullscreen')?.addEventListener('click',()=>document.documentElement.requestFullscreen());function clear(){if(timer){clearTimeout(timer);timer=undefined}}function controls(){pause.textContent=paused?'Resume':'Pause'}function schedule(){clear();if(!paused)timer=setTimeout(()=>move(1),interval)}function render(){const s=slides[i];img.src=s.src;img.style.visibility='visible';count.textContent=s.index+' / '+s.total;controls();schedule()}function move(direction){clear();let next=i+direction;if(next<0)next=loop?slides.length-1:0;if(next>=slides.length){if(loop)next=0;else{paused=true;controls();return}}i=next;if(gap){img.style.visibility='hidden';timer=setTimeout(render,gap)}else render()}function restart(){clear();i=0;paused=false;render()}function toggle(){paused=!paused;controls();schedule()}document.querySelector('#restart').addEventListener('click',restart);document.querySelector('#previous').addEventListener('click',()=>move(-1));document.querySelector('#next').addEventListener('click',()=>move(1));pause.addEventListener('click',toggle);document.addEventListener('keydown',event=>{if(event.key==='ArrowLeft'){event.preventDefault();move(-1)}else if(event.key==='ArrowRight'){event.preventDefault();move(1)}else if(event.code==='Space'){event.preventDefault();toggle()}});render();</script>`;
}
export async function show(directory: string, options: ShowOptions): Promise<void> {
  const interval = Number(options.interval ?? "700"), gap = Number(options.gap ?? "0"); if (!Number.isInteger(interval) || interval < 300) throw new Error("--interval must be an integer of at least 300 ms"); if (!Number.isInteger(gap) || gap < 0) throw new Error("--gap must be a non-negative integer");
  const files = (await fs.readdir(directory, { withFileTypes: true })).filter(e => e.isFile() && [".png", ".jpg", ".jpeg"].includes(path.extname(e.name).toLowerCase())).map(e => e.name);
  const records = await Promise.all(files.map(async file => ({ file, chunk: parseChunk(await readQr(path.join(directory, file))) }))); const projectIds = new Set(records.map(r => r.chunk.projectId)); if (projectIds.size !== 1) throw new Error("Multiple projects detected in slideshow source");
  const requested = options.chunks ? new Set(options.chunks.split(",").map(value => Number(value.trim()))) : undefined; const slides = records.filter(r => !requested || requested.has(r.chunk.chunkIndex)).sort((a, b) => a.chunk.chunkIndex - b.chunk.chunkIndex); if (!slides.length) throw new Error("No matching QR images found");
  const images: SlideshowImage[] = await Promise.all(slides.map(async ({ file, chunk }) => ({ src: `data:image/${path.extname(file).slice(1).toLowerCase() === "png" ? "png" : "jpeg"};base64,${(await fs.readFile(path.join(directory, file))).toString("base64")}`, index: chunk.chunkIndex + 1, total: chunk.totalChunks })));
  const html = buildSlideshowHtml(images, interval, gap, Boolean(options.loop), Boolean(options.fullscreen));
  const output = path.join(os.tmpdir(), `qr-source-show-${randomUUID()}.html`); await fs.writeFile(output, html); console.log(`Opening ${slides.length} QR slides every ${interval} ms.${options.fullscreen ? " Click Enter fullscreen in the opened player." : ""}`);
  if (process.platform === "win32") execFile("cmd", ["/c", "start", "", output]); else if (process.platform === "darwin") execFile("open", [output]); else execFile("xdg-open", [output]);
}
